accent = "#34A65F"
cursor = "#FF7F41"
foreground = "#4FD98C"
background = "#0B1710"
selection_foreground = "#0B1710"
selection_background = "#4FD98C"

color0 = "#000000"
color1 = "#E20342"
color2 = "#C8E967"
color3 = "#7CD699"
color4 = "#34A65F"
color5 = "#3C8F6E"
color6 = "#FF7F41"
color7 = "#1D5C34"
color8 = "#143A22"
color9 = "#CE4F48"
color10 = "#D6FF7A"
color11 = "#FFBE74"
color12 = "#05C79A"
color13 = "#5EE39A"
color14 = "#37B37E"
color15 = "#E9F3EC"
