# primary
background = #0B1710
foreground = #4FD98C
cursor-color = #FF7F41
cursor-text = #0B1710

# normal colors
palette = 0=#000000
palette = 1=#E20342
palette = 2=#C8E967
palette = 3=#7CD699
palette = 4=#34A65F
palette = 5=#3C8F6E
palette = 6=#FF7F41
palette = 7=#1D5C34

# bright colors
palette = 8=#143A22
palette = 9=#CE4F48
palette = 10=#D6FF7A
palette = 11=#FFBE74
palette = 12=#05C79A
palette = 13=#5EE39A
palette = 14=#37B37E
palette = 15=#E9F3EC
