## name: singularity
# author: Dizziee (https://github.com/jjdizz1l)
# variant: "dark"
background              #0B1710
foreground              #4FD98C
selection_foreground    #0B1710
selection_background    #4FD98C
cursor                  #FF7F41
cursor_text_color       #0B1710
active_tab_foreground   #0B1710
active_tab_background   #4FD98C
inactive_tab_foreground #0B1710
inactive_tab_background #4FD98C

# normal colors
color0  #000000
color1  #E20342
color2  #C8E967
color3  #7CD699
color4  #34A65F
color5  #3C8F6E
color6  #FF7F41
color7  #1D5C34

# bright colors
color8  #143A22
color9  #CE4F48
color10 #D6FF7A
color11 #FFBE74
color12 #05C79A
color13 #5EE39A
color14 #37B37E
color15 #E9F3EC
